[package]
name = "snakers-cli"
version = "0.1.0"
edition = "2021"
workspace = ".."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snakers = { path = "../snakers" }
crossterm = "0.27.0"
rand = "0.8.5"
string-builder = "0.2.0"
