[package]
name = "snakers"
version = "0.1.0"
edition = "2021"
workspace = ".."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "snakers"
path = "src/lib.rs"

[dependencies]
rand = "0.8.5"
